# Generated by Django 5.1.2 on 2025-01-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_enroll'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-course_created_at',)},
        ),
    ]
